import { ToolApp, AdSettings, SiteSettings, StoreData } from './types.ts';

export const DEFAULT_AD_LINK = 'https://splendid-garage.com/SJ7fF4';
export const DEFAULT_MAIN_CONTENT_URL = 'https://t.me/premiumtoolsfree1';
export const DEFAULT_ADMIN_PASSWORD = 'Aa123456@';

export const DEFAULT_APPS: ToolApp[] = [
  {
    id: 'app-1',
    name: 'Canva Pro Lifetime 2025',
    logo: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=200&auto=format&fit=crop&q=80',
    category: 'Design & Creative',
    description: 'Unlimited premium templates, brand kits, AI magic studio, and background remover unlocked.',
    version: 'v4.92.0',
    fileSize: '48 MB',
    adLink: DEFAULT_AD_LINK,
    mainContentUrl: DEFAULT_MAIN_CONTENT_URL,
    timerSeconds: 30,
    downloadsCount: 14820,
    rating: 4.9,
    isFeatured: true,
    createdAt: Date.now() - 432000000,
  },
  {
    id: 'app-2',
    name: 'CapCut Pro PC No Watermark',
    logo: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=200&auto=format&fit=crop&q=80',
    category: 'Video Editing',
    description: 'Full version with all VIP transitions, auto-captions, 4K 60FPS export without any watermark.',
    version: 'v5.1.0 PC',
    fileSize: '512 MB',
    adLink: DEFAULT_AD_LINK,
    mainContentUrl: DEFAULT_MAIN_CONTENT_URL,
    timerSeconds: 30,
    downloadsCount: 28940,
    rating: 5.0,
    isFeatured: true,
    createdAt: Date.now() - 345600000,
  },
  {
    id: 'app-3',
    name: 'Adobe Photoshop 2025 Pre-Activated',
    logo: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=200&auto=format&fit=crop&q=80',
    category: 'Design & Creative',
    description: 'Full lifetime activated Photoshop with Generative Fill AI, Neural filters, and multilingual package.',
    version: 'v26.0 Multilingual',
    fileSize: '3.2 GB',
    adLink: DEFAULT_AD_LINK,
    mainContentUrl: DEFAULT_MAIN_CONTENT_URL,
    timerSeconds: 30,
    downloadsCount: 39500,
    rating: 4.9,
    isFeatured: true,
    createdAt: Date.now() - 259200000,
  },
  {
    id: 'app-4',
    name: 'Wondershare Filmora 13 VIP',
    logo: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=200&auto=format&fit=crop&q=80',
    category: 'Video Editing',
    description: 'All AI effects unlocked, speed ramping, keyframe audio ducking, and no subscription required.',
    version: 'v13.6.4',
    fileSize: '490 MB',
    adLink: DEFAULT_AD_LINK,
    mainContentUrl: DEFAULT_MAIN_CONTENT_URL,
    timerSeconds: 30,
    downloadsCount: 19300,
    rating: 4.8,
    isFeatured: false,
    createdAt: Date.now() - 172800000,
  },
  {
    id: 'app-5',
    name: 'Internet Download Manager (IDM) 6.42',
    logo: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=200&auto=format&fit=crop&q=80',
    category: 'Utilities & Tools',
    description: 'Maximum 5x download acceleration, video grabber browser integration, and permanent patch included.',
    version: 'v6.42 Build 18',
    fileSize: '18 MB',
    adLink: DEFAULT_AD_LINK,
    mainContentUrl: DEFAULT_MAIN_CONTENT_URL,
    timerSeconds: 30,
    downloadsCount: 52100,
    rating: 5.0,
    isFeatured: true,
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'app-6',
    name: 'ChatGPT Plus & AI Prompt Tools',
    logo: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=200&auto=format&fit=crop&q=80',
    category: 'AI & Productivity',
    description: 'Exclusive AI prompt suites, Telegram AI automation bots, and full access guides.',
    version: 'v2.5 Suite',
    fileSize: '32 MB',
    adLink: DEFAULT_AD_LINK,
    mainContentUrl: DEFAULT_MAIN_CONTENT_URL,
    timerSeconds: 30,
    downloadsCount: 17400,
    rating: 4.9,
    isFeatured: false,
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'app-7',
    name: 'NordVPN Premium Unlimited',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=200&auto=format&fit=crop&q=80',
    category: 'Security & VPN',
    description: 'High speed 10Gbps servers across 60+ countries, Threat Protection, and Zero-Log DNS.',
    version: 'v7.19.2',
    fileSize: '64 MB',
    adLink: DEFAULT_AD_LINK,
    mainContentUrl: DEFAULT_MAIN_CONTENT_URL,
    timerSeconds: 30,
    downloadsCount: 31200,
    rating: 4.8,
    isFeatured: false,
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'app-8',
    name: 'Telegram Multi-Account Bot Manager',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    category: 'Utilities & Tools',
    description: 'Automate Telegram channel postings, member invites, scheduled auto-replies, and scraping.',
    version: 'v3.1.2 Pro',
    fileSize: '85 MB',
    adLink: DEFAULT_AD_LINK,
    mainContentUrl: DEFAULT_MAIN_CONTENT_URL,
    timerSeconds: 30,
    downloadsCount: 12600,
    rating: 4.9,
    isFeatured: false,
    createdAt: Date.now(),
  },
];

export const DEFAULT_AD_SETTINGS: AdSettings = {
  defaultAdLink: DEFAULT_AD_LINK,
  defaultMainContentUrl: DEFAULT_MAIN_CONTENT_URL,
  defaultTimerSec: 30,
  autoRedirect: true,
  openAdInNewTab: true,
  popunderOnClick: true,
  popunderCooldownMinutes: 1,
  headerScript: `<!-- Adsterra Popunder Ads Script -->\n<script src="https://researchingsweatexit.com/0c/47/ef/0c47ef0c3b62aba1088eb126c11ab894.js"></script>\n<!-- Monetag MultiTag Ads Script -->\n<script src="https://quge5.com/88/tag.min.js" data-zone="286598" async data-cfasync="false"></script>`,
  topBannerCode: `<div style="text-align:center;padding:12px;background:linear-gradient(90deg,rgba(0,242,234,0.08),rgba(255,0,85,0.08));border:1px dashed rgba(0,242,234,0.3);border-radius:12px;font-size:13px;color:#a5f3fc;"><span style="color:#00f2ea;font-weight:bold;">⚡ High-Speed Direct Mirror Active:</span> Click any software below for instant unlocking & maximum speed!</div>`,
  downloadBannerCode: `<div style="text-align:center;padding:10px;background:rgba(0,0,0,0.5);border:1px solid rgba(0,242,234,0.25);border-radius:10px;font-size:12px;color:#e2e8f0;"><span style="color:#f59e0b;font-weight:bold;">💎 Premium Sponsor:</span> Unlimited Cloud Storage & High-Speed Servers Active</div>`,
  floatingSocialBarCode: ``,
  showTopBanner: true,
  showDownloadBanner: true,
  enableImpressionBoost: true,
};

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  siteTitle: 'PREMIUM STORE',
  siteSubtitle: '100% Working Apps & Tools Download',
  telegramChannel: 'https://t.me/premiumtoolsfree1',
  announcement: '🔥 New Premium Tools Added! Join our Telegram Channel for direct updates & instant software keys.',
  showAnnouncement: true,
  adminPassword: DEFAULT_ADMIN_PASSWORD,
};

export const DEFAULT_STORE_DATA: StoreData = {
  apps: DEFAULT_APPS,
  adSettings: DEFAULT_AD_SETTINGS,
  siteSettings: DEFAULT_SITE_SETTINGS,
  lastUpdated: new Date().toISOString(),
};
